[toolchain]
anchor_version = "0.31.1"
rust_version = "1.82.0"

[features]
resolution = true
skip-lint = false

[programs.localnet]
pulsar_payment = "AYR12uFA9XcW2XHyqRYfJLD5nhKoNDqHPk8Yrp3uVMf8"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 10000
skip_deploy = false

